version: '3'
services:
  nginx:
    container_name: nginx
    restart: always
    build:
      dockerfile: dockerfile
      context: ./nginx
    ports:
      - '80:80'
    volumes:
      - ../web:/web
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - code-network
  php-fpm:
    container_name: php-fpm
    restart: on-failure
    build:
      dockerfile: dockerfile
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ../web:/web
    networks:
      - code-network
  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
      - ./web:/web
    environment:
      MYSQL_ROOT_PASSWORD: JoKwlar0JtOTZFL5
    networks:
      - code-network
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - ./web:/web
    networks:
      - code-network
networks:
  code-network:
    driver: bridge
