FROM php:7.3-fpm-alpine

WORKDIR /www

ENV TZ=Asia/Shanghai

COPY ./composer /usr/bin/composer

RUN sed -i "s/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g" /etc/apk/repositories \
    && apk update && apk add --no-cache \
        libpng-dev make gcc musl-dev openssh-server openssh libzip-dev \
		g++ zlib-dev imagemagick imagemagick-dev \
		autoconf vim rabbitmq-c-dev \
    && docker-php-ext-install -j$(nproc) gd bcmath sockets zip pdo_mysql pcntl \
	&& pecl install imagick redis mongodb amqp && docker-php-ext-enable redis imagick mongodb amqp \
    && chmod +x /usr/bin/composer \
    && /usr/bin/composer config -g repo.packagist composer https://mirrors.aliyun.com/composer/

EXPOSE 9000

CMD ["php-fpm"]
