FROM php:7.2-fpm-alpine

WORKDIR /www

ENV TZ=Asia/Shanghai

RUN sed -i "s/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g" /etc/apk/repositories \
    && apk update && apk add \
        libpng-dev make gcc musl-dev \
		g++ zlib-dev imagemagick-dev \
		autoconf \
    && docker-php-ext-install -j$(nproc) gd bcmath sockets zip pdo_mysql \
	&& pecl install imagick redis && docker-php-ext-enable redis imagick \
    && php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php composer-setup.php \
    && rm composer-setup.php \
    && mv composer.phar composer \
    && ./composer config -g repo.packagist composer https://mirrors.aliyun.com/composer/ \
	&& apk del make gcc musl-dev g++ zlib-dev autoconf libpng-dev

EXPOSE 9000

CMD ["php-fpm"]
